#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ]; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="src/httpx tests"

set -x

${PREFIX}ruff check --fix $SOURCE_FILES
${PREFIX}ruff format $SOURCE_FILES
